title: h1alexbel
description: Aliaksei Bialiauski, a.k.a h1alexbel, an Integration Developer,
  Architect, and Open Source advocate.
author: Aliaksei Bialiauski
avatar: /logo.png
email: aliaksei.bialiauski@hey.com
skin: daylight
plugins:
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
paginate: 8
# google_analytics:
disqus: https-h1alexbel-github-io
exclude:
  - scripts/
  - README.md
  - jekyll-theme-hamilton.gemspec
twitter:
  username: h1alexbel
  card: summary
logo: /logo.png
social:
  name: h1alexbel
  links:
    - https://twitter.com/h1alexbel
    - https://github.com/h1alexbel
google_site_verification: u4WXQl0Eu66rsQo2kRdCNx
lang: en
