name: jekyll
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  jekyll:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1.4
      - run: gem install webrick
      - run: gem install faraday-retry
      - run: bundle update
      - run: bundle exec jekyll build
